= Tarefa 2
:stem: latexmath

== Problema 1
{nbsp} Conhecendo as bases para V~16~ e para V~8~, uma base para V~4~ seria

[latexmath] 
++++ 
b_0^4 = \begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        1&1&1&1&0&0&0&0&0&0&0&0&0&0&0&0 \\
\end{array}
++++

[latexmath] 
++++ 
b_1^4 =  \begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0&0&1&1&1&1&0&0&0&0&0&0&0&0 \\
\end{array} 
++++

[latexmath] 
++++ 
b_2^4 = \begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0&0&0&0&0&0&1&1&1&1&0&0&0&0 \\
\end{array}
++++

[latexmath] 
++++ 
b_3^4 = \begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0&0&0&0&0&0&1&1&1&1&0&0&0&0 \\
\end{array}
++++

De forma semelhante, para V~2~ e V~1~ temos

[latexmath] 
++++ 
b_0^2 = \begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        1&1&1&1&1&1&1&1&0&0&0&0&0&0&0&0 \\
\end{array}
++++

[latexmath]  
++++ 
b_1^2 = \begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0&0&0&0&0&0&1&1&1&1&1&1&1&1 \\
\end{array}
++++

e

[latexmath] 
++++ 
b_0^1 = \begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        1&1&1&1&1&1&1&1&1&1&1&1&1&1&1&1 \\
\end{array}
++++

Em geral, uma base para V~k~ consiste em k vetores onde cada vetor b~i~^k^
possui 1 nas posições ki, ki+1, ... , ki+(k-1) e 0 nas demais. Ou seja 

[latexmath] 
++++ 
\hspace{4ex} \begin{array}{ccccccc}
        0&1&\dots&x&x+1&\dots&15
\end{array}
++++

[latexmath]  
++++ 

b_0^k = \begin{array}{|c|c|c|c|c|c|c|}
        \hline
        1&1&\dots&1\hspace{1ex}&\hspace{1ex}0 \hspace{1ex}&\hspace{1ex}\dots\hspace{1ex}&0  \\
\end{array}
++++


[latexmath] 
++++ 
\hspace{4ex} \begin{array}{cccccccc}
        0&\hspace{1.2ex}\dots\hspace{0.7ex}&\hspace{1.5ex}k&k+1&\dots&\hspace{0.5ex}2k-1&2k&\dots&15
\end{array}
++++

[latexmath]  
++++ 

b_1^k = \begin{array}{|c|c|c|c|c|c|c|c|c|}
        \hline
        0&\hspace{0.5ex}\dots\hspace{0.5ex}&\hspace{1ex}1&\hspace{2ex}1\hspace{1ex}&\hspace{0.7ex}\dots\hspace{0.7ex} &\hspace{1.5ex}1\hspace{1.5ex}&\hspace{0.5ex}0\hspace{1.2ex}&\hspace{0.5ex}\dots\hspace{0.5ex}&0 \hspace{0.7ex} \\
\end{array}
++++
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} latexmath:[\vdots]

[latexmath]  
++++ 
\hspace{4ex} \begin{array}{ccccc}
       \hspace{1ex}0\hspace{1ex}&\hspace{1ex}\dots&k^2-k&\dots&15
\end{array}
++++

[latexmath] 
++++ 

b_{k-1}^k = \begin{array}{|c|c|c|c|c|}
        \hline
        \hspace{1ex}0\hspace{1ex}&\hspace{1ex}\dots&\hspace{2ex}1\hspace{1ex}&\dots\hspace{1ex}&1  \\
\end{array}
++++

== Problema 2

{nbsp}Sejam latexmath:[S = s_1, s_2, ..., s_k] e 
latexmath:[T = t_1, t_2, ..., t_j], 
latexmath:[U = Span(S)] e latexmath:[V = Span(T)]

Suponha  latexmath:[\left\{ c| c \in U \cup V \right\} ]. Então
os elementos gerados por latexmath:[C] são da forma 
latexmath:[\alpha_1 s_1+\alpha_2 s_2+...+\alpha_k s_k+\beta_1 t_1+\beta_2 t_2+...+\beta_j t_j ]

Mas, 

latexmath:[\alpha_1 s_1+\alpha_2 s_2+...+\alpha_k s_k \in U ]

e 

[latexmath]
++++
\beta_1 t_1+\beta_2 t_2+...+\beta_j t_j \in V 
++++

Logo, os espaços gerados por latexmath:[C] são da forma latexmath:[W = \left\{ a + b | a \in U \wedge  b \in V \right\} ].

Portanto, latexmath:[C] é um conjunto de geradores para latexmath:[U \oplus V] e a união de uma base para 
latexmath:[U] e uma base para latexmath:[V] é uma base para latexmath:[U \oplus V].


== Problema 3

{nbsp}Sabendo que 
[latexmath] 
++++ 
b_0^{16} = \begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        1&0&0&0&0&0&0&0&0&0&0&0&0&0&0&0 \\
\end{array}
++++

é ortogonal a
[latexmath] 
++++ 
b_0^{8} = \begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        1&1&0&0&0&0&0&0&0&0&0&0&0&0&0&0 \\
\end{array}
++++

[latexmath] 
++++ 
b_1^{8} = \begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&1&1&0&0&0&0&0&0&0&0&0&0&0&0 \\
\end{array}
++++

...

[latexmath] 
++++ 
b_7^{8} = \begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0&0&0&0&0&0&0&0&0&0&0&0&1&1 \\
\end{array}
++++

Temos que a projeção de b~0~^16^ 
ao longo de b~0~^8^
é

[latexmath] 
++++ 
\frac{<b_0^{16} , b_0^{8} >}{ < b_0^{8}, b_0^{8} > }
\cdot b_0^{8}
++++

Substituindo fica
[latexmath] 
++++ 
\frac{(1)(1)+(0)(1)+(0)(0)+...+(0)(0)}
{(1)(1)+(1)(1)+(0)(0)+...+(0)(0)}
\cdot b_0^{8}
++++

[latexmath] 
++++ 
=
\frac{1}{2}
\cdot b_0^{8}
++++

Então, a projeção de b~0~^16^ 
ao longo de b~0~^8^ 
é

[latexmath] 
++++ 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0.5&0.5&0&0&0&0&0&0&0&0&0&0&0&0&0&0 \\
\end{array}
++++

Ao efetuarmos b~0~^16^ 
- b~0~^8^
para encontrarmos o complemento, temos

[latexmath] 
++++ 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0.5&-0.5&0&0&0&0&0&0&0&0&0&0&0&0&0&0 \\
\end{array}
++++

O que nos dá o primeiro vetor base. Isto é,
[latexmath] 
++++ 
w_0^{8} = \begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0.5&-0.5&0&0&0&0&0&0&0&0&0&0&0&0&0&0 \\
\end{array}
++++

Projetando b~1~^16^
ortogonal a V~8~
apenas vamos obter o negativo de w~0~^8^.
Vamos então prosseguir com a projeção de b~2~^16^.
Notemos que ele é ortogonal a todos os vetores exceto b~1~^8^.
Deste modo,

[latexmath] 
++++ 
\frac{<b_2^{16} , b_1^{8} >}{ < b_1^{8}, b_1^{8} > }
\cdot b_1^{8}
= 
\frac{(0)(0)+(0)(0)+(1)(1)+(0)(1)+...+(0)(0)}
{(0)(0)+(0)(0)+(1)(1)+(1)(1)+...+(0)(0)}
\cdot b_1^{8}
=
\frac{1}{2}
\cdot b_1^{8}
++++

Então, a projeção de b~2~^16^ 
ao longo de b~1~^8^ 
é

[latexmath] 
++++ 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0.5&0.5&0&0&0&0&0&0&0&0&0&0&0&0 \\
\end{array}
++++

Logo, nosso segundo vetor base w~1~^8^ =

[latexmath] 
++++ 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0.5&-0.5&0&0&0&0&0&0&0&0&0&0&0&0 \\
\end{array}
++++

Podemos perceber que o coeficiente obtido sempre será 1/2, alterando no cálculo apenas o vetor b~i~^8^
e b~i~^16^,
já que todos possuem a mesma forma.
Repetindo, portanto, o processo ao realizar o cálculo, 
obtemos os seguintes vetores wavelet. Isto é, a base de W~8~
ortogonal a base de V~8~
em  V~16~:

[latexmath] 
++++ 
w_0^8 = 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0.5&-0.5&0&0&0&0&0&0&0&0&0&0&0&0&0&0 \\
\end{array}
++++

[latexmath] 
++++ 
w_1^8 = 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0.5&-0.5&0&0&0&0&0&0&0&0&0&0&0&0 \\
\end{array}
++++


[latexmath] 
++++ 
w_2^8 = 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0&0&0.5&-0.5&0&0&0&0&0&0&0&0&0&0 \\
\end{array}
++++


[latexmath] 
++++ 
w_3^8 = 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0&0&0&0&0.5&-0.5&0&0&0&0&0&0&0&0 \\
\end{array}
++++

[latexmath] 
++++ 
w_4^8 = 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0&0&0&0&0&0&0.5&-0.5&0&0&0&0&0&0 \\
\end{array}
++++

[latexmath] 
++++ 
w_5^8 = 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0&0&0&0&0&0&0&0&0.5&-0.5&0&0&0&0 \\
\end{array}
++++

[latexmath] 
++++ 
w_6^8 = 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0&0&0&0&0&0&0&0&0&0&0.5&-0.5&0&0 \\
\end{array}
++++

[latexmath] 
++++ 
w_7^8 = 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0&0&0&0&0&0&0&0&0&0&0&0&0.5&-0.5 \\
\end{array}
++++



== Problema 4

Utilizemos a mesma lógica expressa na questão anterior para encontrarmos os vetores que
compreendem a base W~4~, 
complemento ortogonal de V~4~
em V~8~,
bem como os vetores que compreendem a base W~2~ e W~1~.

===== *1. Encontrar vetores que compreendem base W~4~*

*1.1. Vetor w~0~^4^
.*


Sabendo que b~0~^8^
é ortogonal a b~0~^4^,
b~1~^4^, b~2~^4^, b~3~^4^.

Temos que a projeção de b~0~^8^
ao longo de b~0~^4^ é

[latexmath] 
++++ 
\frac{<b_0^{8} , b_0^{4} >}{ < b_0^{4}, b_0^{4} > }
\cdot b_0^{4}
=
\frac{(1)(1)+(1)(1)+(0)(1)+(0)(1)+...+(0)(0)}
{(1)(1)+(1)(1)+(1)(1)+(1)(1)+...+(0)(0)}
\cdot b_0^{4}
++++

[latexmath] 
++++ 
=
\frac{1}{2}
\cdot b_0^{4}
++++

Então, a projeção de b~0~^8^ 
ao longo de b~0~^4^ 
é

[latexmath] 
++++ 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0.5&0.5&0.5&0.5&0&0&0&0&0&0&0&0&0&0&0&0 \\
\end{array}
++++

O complemento é dado por 
w~0~^4^ = b~0~^8^ - b~0~^4^. 
Logo, 

[latexmath] 
++++ 
w_0^4 = 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0.5&0.5&-0.5&-0.5&0&0&0&0&0&0&0&0&0&0&0&0 \\
\end{array}
++++




*1.2. Vetor w~1~^4^
.*

Temos que a projeção de b~2~^8^
ao longo de b~1~^4^ é

[latexmath] 
++++ 
\frac{<b_2^{8} , b_1^{4} >}{ < b_1^{4}, b_1^{4} > }
\cdot b_1^{4}
=
\frac{(0)(0)+...+(1)(1)+(1)(1)+(0)(1)+(0)(1)+...+(0)(0)}
{(0)(0)+...+(1)(1)+(1)(1)+(1)(1)+(1)(1)+...+(0)(0)}
\cdot b_1^{4}
++++

[latexmath] 
++++ 
=
\frac{1}{2}
\cdot b_1^{4}
++++

Então, a projeção de b~2~^8^ 
ao longo de b~1~^4^ 
é

[latexmath] 
++++ 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0&0&0.5&0.5&0.5&0.5&0&0&0&0&0&0&0&0 \\
\end{array}
++++

O complemento é dado por 
w~1~^4^ = b~2~^8^ - b~1~^4^.
Logo, 
[latexmath] 
++++ 
w_1^4 = 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0&0&0.5&0.5&-0.5&-0.5&0&0&0&0&0&0&0&0 \\
\end{array}
++++



*1.3. Vetor w~2~^4^
.*

Temos que a projeção de b~4~^8^
ao longo de b~2~^4^ é

[latexmath] 
++++ 
\frac{<b_4^{8} , b_2^{4} >}{ < b_2^{4}, b_2^{4} > }
\cdot b_2^{4}
=
\frac{(0)(0)+...+(1)(1)+(1)(1)+(0)(1)+(0)(1)+...+(0)(0)}
{(0)(0)+...+(1)(1)+(1)(1)+(1)(1)+(1)(1)+...+(0)(0)}
\cdot b_2^{4}
++++

[latexmath] 
++++ 
=
\frac{1}{2}
\cdot b_2^{4}
++++

Então, a projeção de b~4~^8^ 
ao longo de b~2~^4^ 
é

[latexmath] 
++++ 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0&0&0&0&0&0&0.5&0.5&0.5&0.5&0&0&0&0 \\
\end{array}
++++

O complemento é dado por 
w~2~^4^ = b~4~^8^ - b~2~^4^.
Logo, 
[latexmath] 
++++ 
w_2^4 = 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0&0&0&0&0&0&0.5&0.5&-0.5&-0.5&0&0&0&0 \\
\end{array}
++++


*1.4. Vetor w~3~^4^
.*

Temos que a projeção de b~6~^8^
ao longo de b~3~^4^ é

[latexmath] 
++++ 
\frac{<b_6^{8} , b_3^{4} >}{ < b_3^{4}, b_3^{4} > }
\cdot b_3^{4}
=
\frac{(0)(0)+(0)(0)+...+(1)(1)+(1)(1)+(0)(1)+(0)(1)}
{(0)(0)+(0)(0)+...+(1)(1)+(1)(1)+(1)(1)+(1)(1)}
\cdot b_3^{4}
++++

[latexmath] 
++++ 
=
\frac{1}{2}
\cdot b_3^{4}
++++

Então, a projeção de b~6~^8^ 
ao longo de b~3~^4^ 
é

[latexmath] 
++++ 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0&0&0&0&0&0&0&0&0&0&0.5&0.5&0.5&0.5 \\
\end{array}
++++

O complemento é dado por 
w~3~^4^ = b~6~^8^ - b~3~^4^.
Logo, 
[latexmath] 
++++ 
w_3^4 = 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0&0&0&0&0&0&0&0&0&0&0.5&0.5&-0.5&-0.5 \\
\end{array}
++++

*1.5. Síntese
.*

Portanto, os vetores wavelet da base de W4 ortogonal a base de V4 em V8 é:

[latexmath] 
++++ 
w_0^4 = 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0.5&0.5&-0.5&-0.5&0&0&0&0&0&0&0&0&0&0&0&0 \\
\end{array}
++++

[latexmath] 
++++ 
w_1^4 = 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0&0&0.5&0.5&-0.5&-0.5&0&0&0&0&0&0&0&0 \\
\end{array}
++++

[latexmath] 
++++ 
w_2^4 = 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0&0&0&0&0&0&0.5&0.5&-0.5&-0.5&0&0&0&0 \\
\end{array}
++++

[latexmath] 
++++ 
w_3^4 = 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0&0&0&0&0&0&0&0&0&0&0.5&0.5&-0.5&-0.5 \\
\end{array}
++++

.
[%hardbreaks]

===== *2. Encontrar vetores que compreendem a base W~2~*

*2.1. Vetor w~0~^2^
.*

Sabendo que b~0~^4^
é ortogonal a b~0~^2^,
b~1~^2^.

Temos que a projeção de b~0~^4^
ao longo de b~0~^2^ é

[latexmath] 
++++ 
\frac{<b_0^{4} , b_0^{2} >}{ < b_0^{2}, b_0^{2} > }
\cdot b_0^{2}
=
\frac{(1)(1)+(1)(1)+(1)(1)+(1)(1)+(0)(1)+...+(0)(0)}
{(1)(1)+(1)(1)+(1)(1)+(1)(1)+(1)(1)+...+(0)(0)}
\cdot b_0^{2}
++++

[latexmath] 
++++ 
=
\frac{1}{2}
\cdot b_0^{2}
++++

Então, a projeção de b~0~^4^ 
ao longo de b~0~^2^ 
é

[latexmath] 
++++ 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0.5&0.5&0.5&0.5&0.5&0.5&0.5&0.5&0&0&0&0&0&0&0&0 \\
\end{array}
++++

O complemento é dado por 
w~0~^2^ = b~0~^4^ - b~0~^2^. 
Logo, 

[latexmath] 
++++ 
w_0^2 = 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0.5&0.5&0.5&0.5&-0.5&-0.5&-0.5&-0.5&0&0&0&0&0&0&0&0 \\
\end{array}
++++

*2.2. Vetor w~1~^2^
.*

Temos que a projeção de b~2~^4^
ao longo de b~1~^2^ é

[latexmath] 
++++ 
\frac{<b_2^{4} , b_1^{2} >}{ < b_1^{2}, b_1^{2} > }
\cdot b_1^{2}
=
\frac{(0)(0)+...+(1)(1)+(1)(1)+(1)(1)+(1)(1)+(0)(1)}
{(0)(0)+...+(1)(1)+(1)(1)+(1)(1)+(1)(1)+(1)(1)}
\cdot b_1^{2}
++++

[latexmath] 
++++ 
=
\frac{1}{2}
\cdot b_1^{2}
++++

Então, a projeção de b~2~^4^ 
ao longo de b~1~^2^ 
é

[latexmath] 
++++ 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0&0&0&0&0&0&0.5&0.5&0.5&0.5&0.5&0.5&0.5&0.5 \\
\end{array}
++++

O complemento é dado por 
w~1~^2^ = b~2~^4^ - b~1~^2^. 
Logo, 

[latexmath] 
++++ 
w_1^2 = 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0&0&0&0&0&0&0.5&0.5&0.5&0.5&-0.5&-0.5&-0.5&-0.5 \\
\end{array}
++++

*2.3. Síntese
.*

Portanto, os vetores wavelet da base de W2 ortogonal a base de V2 em V4 é:

[latexmath] 
++++ 
w_0^2 = 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0.5&0.5&0.5&0.5&-0.5&-0.5&-0.5&-0.5&0&0&0&0&0&0&0&0 \\
\end{array}
++++

[latexmath] 
++++ 
w_1^2 = 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0&0&0&0&0&0&0&0&0.5&0.5&0.5&0.5&-0.5&-0.5&-0.5&-0.5 \\
\end{array}
++++

.
[%hardbreaks]

===== *3. Encontrar o vetor que compreende a base W~1~*

Temos que a projeção de b~0~^2^
ao longo de b~0~^1^ é

[latexmath] 
++++ 
\frac{<b_0^{2} , b_0^{1} >}{ < b_0^{1}, b_0^{1} > }
\cdot b_0^{1}
=
\frac{(1)(1)+(1)(1)+(1)(1)+(1)(1)+(1)(1)+...+(0)(1)}
{(1)(1)+...+(1)(1)+(1)(1)+(1)(1)+(1)(1)+(1)(1)}
\cdot b_0^{1}
++++

[latexmath] 
++++ 
=
\frac{1}{2}
\cdot b_0^{1}
++++

Então, a projeção de b~0~^2^ 
ao longo de b~0~^1^ 
é

[latexmath] 
++++ 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0.5&0.5&0.5&0.5&0.5&0.5&0.5&0.5&0.5&0.5&0.5&0.5&0.5&0.5&0.5&0.5
\end{array}
++++

O complemento é dado por 
w~0~^1^ = b~0~^2^ - b~0~^1^. 
Logo, 

[latexmath] 
++++ 
w_0^1 = 
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
        \hline
        0.5&0.5&0.5&0.5&0.5&0.5&0.5&0.5&-0.5&-0.5&-0.5&-0.5&-0.5&-0.5&-0.5&-0.5 \\
\end{array}
++++

== Problema 5
Seja latexmath:[v] o vetor que representa 
a imagem de dimensão 1 de modo que
[latexmath]
++++
\[ v = 

[ \begin{array}{cccccccccccccccc}
        4&5&3&7&4&5&2&3&9&7&3&5&0&0&0&0 \\
\end{array}]
\]
++++

Calculando o coeficiente x~0~ para latexmath:[v], temos

[latexmath]
++++
x_0 = \frac{<v, b_0^8>}{ <b_0^8, b_0^8>}

    =
\frac{(4*1)+(5*1)+(3*0)+(7*0)+\dots+(0*0)}{(1*1)+(1*1)+(0*0)+(0*0)+(0*0)+\dots+(0*0)}

++++

[latexmath]
++++
    =
\frac{9}{2}

++++

== Problema 6 

Calculando o coeficiente y~0~ para latexmath:[v], temos

[latexmath]
++++
y_0 = \frac{<v, w_0^8>}{<w_0^8, w_0^8>}
 = 
 \frac{(4*0.5)+(5*(-0.5))+(3*0)+(7*0)+\dots+(0*0)}{(0.5)^2+(-0.5)^2+(0*0)^2+(0*0)^2+\dots+(0*0)^2}
++++

[latexmath]
++++
= \frac{2-2.5}{0.25+0.25} = \frac{-0.5}{0.5} = -1

++++